import { premedProfileSchema, type PremedProfileInput } from "@/lib/validation/premed-profile";

export const sampleProfiles: PremedProfileInput[] = [
  premedProfileSchema.parse({
    fullName: "Maya Thompson",
    email: "demo@premedgapyearpredictor.com",
    stateOfResidence: "North Carolina",
    collegeName: "Duke University",
    graduationYear: 2026,
    currentYear: "SENIOR",
    major: "Neuroscience",
    minor: "Spanish",
    honorsProgram: true,
    cumulativeGpa: 3.84,
    scienceGpa: 3.8,
    mcatTotal: 516,
    mcatChemPhys: 129,
    mcatCars: 128,
    mcatBioBiochem: 129,
    mcatPsychSoc: 130,
    numberOfWithdrawals: 0,
    numberOfCsOrLower: 0,
    upwardGradeTrend: true,
    schoolRigor: "HIGH",
    paidClinicalHours: 240,
    clinicalVolunteerHours: 160,
    patientFacingHours: 380,
    clinicalExperienceTypes: ["Medical assistant", "Hospital volunteer"],
    customClinicalExperienceTypes: ["Free clinic intake"],
    clinicalRoleDescription:
      "I worked as a dermatology medical assistant and then shifted into a student-run free clinic role where I learned how longitudinal patient follow-up changes trust.",
    shadowingTotalHours: 65,
    physiciansShadowed: 4,
    primaryCareShadowingHours: 18,
    specialtyShadowingHours: 47,
    virtualShadowingHours: 8,
    shadowingReflection:
      "Primary care shadowing made the counseling and continuity side of medicine feel real in a way specialty days did not.",
    researchHours: 420,
    researchProjectsCount: 2,
    researchType: "CLINICAL",
    postersPresentationsCount: 2,
    publicationsCount: 1,
    abstractsCount: 1,
    researchContribution:
      "I coordinated data cleaning and statistical analysis for a cardiology outcomes project and presented the final abstract at a regional meeting.",
    nonClinicalVolunteerHours: 210,
    underservedServiceHours: 145,
    serviceLeadership: true,
    serviceCategories: ["Food security", "Public health outreach"],
    customServiceCategories: ["Refugee resettlement"],
    serviceExperience:
      "My most meaningful service has been weekly work with a refugee support network helping families navigate school enrollment and clinic follow-up.",
    leadershipHours: 180,
    leadershipRolesCount: 2,
    highestLeadershipLevel: "PRESIDENT",
    leadershipDescription:
      "I served as president of our campus health equity collaborative and built a volunteer pipeline for new students.",
    paidNonClinicalWorkHours: 420,
    paidClinicalWorkHours: 240,
    employmentWhileInSchool: true,
    workedDuringSemesters: true,
    jobDescription:
      "I also worked part-time in admissions, which helped with communication and schedule management while balancing pre-med coursework.",
    clubsOrganizations: ["Health Equity Collaborative", "AMSA"],
    hobbiesInterests: ["Distance running", "Cooking"],
    sports: ["Half marathon training"],
    creativeActivities: ["Photography"],
    longTermCommitments: ["Refugee family mentorship"],
    distinctivenessFactor:
      "The strongest through-line in my profile is multilingual community-facing service tied to immigrant families.",
    gapYearPlans: "",
    plannedApplicationCycle: "2026-2027",
    plannedSchoolListSize: 24,
    applicationInterest: "BOTH",
    researchHeavyPreference: false,
    serviceHeavyPreference: true,
    stateSchoolPriority: true,
    committeeLetter: false,
    scienceProfessorLetters: 2,
    nonScienceProfessorLetters: 1,
    researchMentorLetters: 1,
    clinicalSupervisorLetters: 1,
    serviceWorkSupervisorLetters: 1,
    letterStrength: "STRONG",
    personalStatementReadiness: "STRONG_DRAFT",
    activitiesReadiness: "READY",
    schoolListReadiness: "DRAFTED",
  }),
  premedProfileSchema.parse({
    fullName: "Jordan Patel",
    email: "demo@premedgapyearpredictor.com",
    stateOfResidence: "Illinois",
    collegeName: "University of Illinois Urbana-Champaign",
    graduationYear: 2026,
    currentYear: "SENIOR",
    major: "Molecular and Cellular Biology",
    minor: "",
    honorsProgram: false,
    cumulativeGpa: 3.57,
    scienceGpa: 3.48,
    mcatTotal: 507,
    mcatChemPhys: 126,
    mcatCars: 127,
    mcatBioBiochem: 127,
    mcatPsychSoc: 127,
    numberOfWithdrawals: 1,
    numberOfCsOrLower: 2,
    upwardGradeTrend: true,
    schoolRigor: "MEDIUM",
    paidClinicalHours: 110,
    clinicalVolunteerHours: 55,
    patientFacingHours: 145,
    clinicalExperienceTypes: ["Scribe"],
    customClinicalExperienceTypes: [],
    clinicalRoleDescription:
      "I have scribed in a busy emergency department and learned how team communication changes under pressure.",
    shadowingTotalHours: 24,
    physiciansShadowed: 2,
    primaryCareShadowingHours: 6,
    specialtyShadowingHours: 18,
    virtualShadowingHours: 6,
    shadowingReflection:
      "The ED confirmed that I like clinical pace, but I still need broader exposure to outpatient practice.",
    researchHours: 160,
    researchProjectsCount: 1,
    researchType: "BASIC_SCIENCE",
    postersPresentationsCount: 1,
    publicationsCount: 0,
    abstractsCount: 0,
    researchContribution:
      "I maintained cell culture experiments and contributed to weekly lab meetings, but I have not yet produced a publication-level output.",
    nonClinicalVolunteerHours: 80,
    underservedServiceHours: 36,
    serviceLeadership: false,
    serviceCategories: ["Education or tutoring"],
    customServiceCategories: [],
    serviceExperience:
      "I tutor local high school students in biology and chemistry through a weekly campus outreach program.",
    leadershipHours: 65,
    leadershipRolesCount: 1,
    highestLeadershipLevel: "COMMITTEE",
    leadershipDescription:
      "I coordinated one exam-prep initiative for our tutoring organization but have not held a top campus role.",
    paidNonClinicalWorkHours: 520,
    paidClinicalWorkHours: 110,
    employmentWhileInSchool: true,
    workedDuringSemesters: true,
    jobDescription:
      "I worked 15 to 20 hours weekly in retail throughout sophomore and junior year to help cover living expenses.",
    clubsOrganizations: ["Pre-med club", "Biology honors society"],
    hobbiesInterests: ["Basketball", "Podcasting"],
    sports: ["Intramural basketball"],
    creativeActivities: ["Audio editing"],
    longTermCommitments: ["Family caregiving"],
    distinctivenessFactor:
      "Working throughout school while supporting family responsibilities has shaped most of my time management decisions.",
    gapYearPlans:
      "If I take a gap year, I would continue clinical scribing, add service work, and revisit the MCAT after structured prep.",
    plannedApplicationCycle: "2026-2027",
    plannedSchoolListSize: 18,
    applicationInterest: "BOTH",
    researchHeavyPreference: false,
    serviceHeavyPreference: true,
    stateSchoolPriority: true,
    committeeLetter: false,
    scienceProfessorLetters: 2,
    nonScienceProfessorLetters: 0,
    researchMentorLetters: 0,
    clinicalSupervisorLetters: 1,
    serviceWorkSupervisorLetters: 0,
    letterStrength: "AVERAGE",
    personalStatementReadiness: "DRAFTING",
    activitiesReadiness: "IN_PROGRESS",
    schoolListReadiness: "NOT_STARTED",
  }),
  premedProfileSchema.parse({
    fullName: "Elena Brooks",
    email: "demo@premedgapyearpredictor.com",
    stateOfResidence: "Texas",
    collegeName: "University of Houston",
    graduationYear: 2025,
    currentYear: "GRADUATE",
    major: "Psychology",
    minor: "Public Health",
    honorsProgram: false,
    cumulativeGpa: 3.31,
    scienceGpa: 3.19,
    mcatTotal: 501,
    mcatChemPhys: 124,
    mcatCars: 126,
    mcatBioBiochem: 125,
    mcatPsychSoc: 126,
    numberOfWithdrawals: 2,
    numberOfCsOrLower: 4,
    upwardGradeTrend: false,
    schoolRigor: "MEDIUM",
    paidClinicalHours: 40,
    clinicalVolunteerHours: 35,
    patientFacingHours: 70,
    clinicalExperienceTypes: ["Hospital volunteer"],
    customClinicalExperienceTypes: [],
    clinicalRoleDescription:
      "I have some patient transport and volunteer bedside support experience, but not yet a deep clinical role.",
    shadowingTotalHours: 12,
    physiciansShadowed: 1,
    primaryCareShadowingHours: 0,
    specialtyShadowingHours: 12,
    virtualShadowingHours: 8,
    shadowingReflection:
      "I understand that I need more direct physician observation before applying.",
    researchHours: 40,
    researchProjectsCount: 1,
    researchType: "PUBLIC_HEALTH",
    postersPresentationsCount: 0,
    publicationsCount: 0,
    abstractsCount: 0,
    researchContribution:
      "My exposure to research has been limited to helping with survey coding for a short public-health project.",
    nonClinicalVolunteerHours: 42,
    underservedServiceHours: 18,
    serviceLeadership: false,
    serviceCategories: ["Public health outreach"],
    customServiceCategories: [],
    serviceExperience:
      "Most of my service experience has been episodic volunteering through health fairs rather than long-term weekly work.",
    leadershipHours: 28,
    leadershipRolesCount: 1,
    highestLeadershipLevel: "MEMBER",
    leadershipDescription:
      "I have participated in club activities but have not yet taken on a meaningful leadership role.",
    paidNonClinicalWorkHours: 780,
    paidClinicalWorkHours: 40,
    employmentWhileInSchool: true,
    workedDuringSemesters: true,
    jobDescription:
      "I have worked consistently in hospitality, which shows responsibility but has left less room for clinical and service growth.",
    clubsOrganizations: ["Psychology club"],
    hobbiesInterests: ["Baking", "Yoga"],
    sports: [],
    creativeActivities: ["Poetry"],
    longTermCommitments: ["Helping with younger siblings"],
    distinctivenessFactor:
      "My profile shows resilience and steady work, but it does not yet have enough depth in the highest-value pre-med areas.",
    gapYearPlans:
      "I would likely need dedicated time for academic repair, more clinical exposure, and stronger service consistency before applying.",
    plannedApplicationCycle: "2027-2028",
    plannedSchoolListSize: 12,
    applicationInterest: "DO",
    researchHeavyPreference: false,
    serviceHeavyPreference: false,
    stateSchoolPriority: true,
    committeeLetter: false,
    scienceProfessorLetters: 1,
    nonScienceProfessorLetters: 0,
    researchMentorLetters: 0,
    clinicalSupervisorLetters: 0,
    serviceWorkSupervisorLetters: 1,
    letterStrength: "AVERAGE",
    personalStatementReadiness: "NOT_STARTED",
    activitiesReadiness: "NOT_STARTED",
    schoolListReadiness: "NOT_STARTED",
  }),
];
